name: Docker Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker build -t continuous-delivery-lab:${{ github.sha }} .
